#!/bin/bash

### BEGIN INIT INFO
# Provides:          appserver
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts appserver
# Description:       starts appserver using nohup
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
BASE_PATH='/opt/appserver'
DAEMON="${BASE_PATH}/bin/php"
DAEMON_OPTS="${BASE_PATH}/server.php"
NAME="appserver"
DESC="appserver"
PIDFILE="/var/run/${NAME}.pid"
NOHUP=$(which nohup)
if [ -f $PIDFILE ]; then
    PID=$(cat $PIDFILE)
else
    PID="0"
fi

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC ... "
	$NOHUP $DAEMON $DAEMON_OPTS 2>1 >/dev/null </dev/null &
	if [ $? -eq 0 ];
	then
	    echo $! > $PIDFILE
	    echo "PID($!)"
	else
	    echo -n "failed to start appserver"
	    exit 1
	fi
	;;
  stop)
	if [ "$PID" != "0" ]; then
	    echo -n "Killing $DESC ... "
	    kill -s TERM $PID
	    if [ $? -eq 0 ]; then
	        rm -rf $PIDFILE
	        echo "PID($PID) killed"
	    else
	        echo "failed to kill $DESC PID($PID)"
	        exit 2
	    fi
	else
	    echo "$DESC not running"
	    exit 1
	fi
	;;
  status)
    if [ "$PID" != "0" ]; then
        echo "$DESC PID($PID)"
    else
        echo "$DESC not running"
        exit 1
    fi
    ;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status|force-reload}" >&2
	exit 1
	;;
esac

exit 0
