#!/bin/sh

/opt/appserver/bin/pecl upgrade pthreads
/opt/appserver/bin/pecl upgrade memcached

curl -sS https://getcomposer.org/installer | sudo /opt/appserver/bin/php -- --install-dir /opt/appserver/bin
echo "/opt/appserver/bin/php /opt/appserver/bin/composer.phar" >> /opt/appserver/bin/composer

/opt/appserver/bin/composer --working-dir=/opt/appserver/app/code update

chmod a+x /opt/appserver/appserver
chmod a+x -R /opt/appserver/bin
#ln -s /opt/appserver/appserver /usr/local/bin/appserver

exit 0