#!/bin/sh

/opt/appserver/bin/pecl upgrade pthreads
/opt/appserver/bin/pecl upgrade memcached

curl -sS https://getcomposer.org/installer | sudo /opt/appserver/bin/php -- --install-dir /opt/appserver/bin

chmod 755 /opt/appserver/appserver
chmod 755 -R /opt/appserver/bin

/opt/appserver/bin/composer update

exit 0
