#!/bin/sh

/opt/appserver/sbin/appserverctl stop
/opt/appserver/sbin/watcherctl stop
/opt/appserver/sbin/phpfpmctl stop
/opt/appserver/sbin/memcachedctl stop
/opt/appserver/sbin/redisctl stop

exit 0
