#!/bin/bash

echo "flush_all" | nc 127.0.0.1 11211 > /dev/null

APPSERVER_ROOT="/opt/appserver"

export LIBRARY_PATH=$APPSERVER_ROOT/lib

export DYLD_LIBRARY_PATH=$LIBRARY_PATH:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LIBRARY_PATH:$LD_LIBRARY_PATH

cd $APPSERVER_ROOT
$APPSERVER_ROOT/bin/php server.php